name: Deploy Advance Spark Notebook

on:
  push:
    branches:
      - main
    paths:
      - "spark_demo/advance-spark.ipynb"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Databricks CLI
        run: |
          pip install databricks-cli

      - name: Configure Databricks
        env:
          DATABRICK_ADVANCE: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          mkdir -p ~/.databricks
          echo "[DEFAULT]" > ~/.databrickscfg
          echo "host=$DATABRICKS_HOST" >> ~/.databrickscfg
          echo "token=$DATABRICKS_TOKEN" >> ~/.databrickscfg

      - name: Upload Notebook
        run: |
          databricks workspace import \
          spark-demo/advance-spark.ipynb \
          /Shared/advance-spark \
          --language PYTHON \
          --format JUPYTER \
          --overwrite
